### ISSUE TITLE
Expected Usage

### ISSUE THREAD

**Issue by RLovelett** [skyscrapers/terraform-state#11]
I have a couple of questions about how you all intended this module to be used. I have an existing Terraform definition with an existing state for two workspaces: `default` and `development`.

```hcl
terraform {
  backend "s3" {
    encrypt        = true
    bucket         = "app-terraform-remote-state-storage-s3"
    dynamodb_table = "app-terraform-remote-state-lock-dynamo"
    region         = "us-west-2"
    key            = "terraform.tfstate"
  }
}
```

Is the expectation that I'd add this as a module, change the `bucket` and `dynamodb_table` values to match `module.s3.bucket_id` and `module.s3.locktable_id` and all would be fine? Or is there some other expected workflow? e.g.

```patch
diff --git a/main.tf b/main.tf
index 93526f6..57bf1b8 100644
--- a/terraform.tf
+++ b/terraform.tf
@@ -17,14 +17,21 @@ provider "template" {
   version = "~> 1.0"
 }
 
+module "s3" {
+  source  = "github.com/skyscrapers/terraform-state//s3?ref=3.0.0"
+  project = "app"
+}
+
 terraform {
   required_version = "~> 0.11"
 
   backend "s3" {
     encrypt        = true
-    bucket         = "app-terraform-remote-state-storage-s3"
-    dynamodb_table = "app-terraform-remote-state-lock-dynamo"
+    bucket         = "terraform-remote-state-app"
+    dynamodb_table = "terraform-remote-state-lock-app"
     region         = "us-west-2"
     key            = "terraform.tfstate"
   }
 }
```

The reason I ask is that it seems to be a bit of a chicken and egg scenario. I need these resources before I can provision my environment so I can store state and yet it is will be part of the environment too.

Also, what is the expected way to handle multiple workspaces? It seems like switching workspaces will cause the environment to try and reprovision the state storage resources.

**Comment by iuriaranda** [comment]
Hello @RLovelett,

Indeed it's a chicken and egg problem. We handle it by setting up the S3 state module in a separated Terraform configuration with a local state file.

So we end up having a special "bootstrap" Terraform configuration that just sets up the state S3 bucket (and a bunch of other stuff in our case) with a local state file that is committed to source control, then we have all the other Terraform configurations that use the S3 bucket and DynamoDB table for their remote state. Of course the "bootstrap" configuration is applied before anything else.

By doing it this way, all the Terraform configurations except the "bootstrap" one can have multiple workspaces.

Does this clear up your questions?

**Comment by RLovelett** [comment]
Yes it does @iuriaranda. That is largely what we already have in place. Though your S3 configuration, with the forced encryption and preventing public access, is better than ours. So I'll go ahead refactor our bootstrap configuration to use this module.

One last question, and this is mostly a best practice thing. Do you have a single "bootstrap" configuration and _all_ your projects use that? Or do you have multiple "bootstrap"s per project? Right now we use a single bootstrap for all of our projects and just use the key path to store each project.

**Comment by iuriaranda** [comment]
This is how we structure it:

- we have a "bootstrap" configuration per customer
- each customer has multiple Terraform configurations
- for each customer, all Terraform configurations use the same customer-specific S3 bucket created in the "bootstrap" module, but with different keys to avoid conflicts

We do it like this so our customers own and have access to their own Terraform state files, but if that is not a requirement in your case, a single state S3 bucket should be enough.

If by "projects" you mean Terraform configurations, I would definitely discourage you to have a separated "bootstrap" configuration for each of them, as that would be a bit overkill imo.

I hope this helped you 🙂

**Comment by iuriaranda** [comment]
I'll go ahead and close this issue for now, but if you have any more questions don't hesitate to post it here or create a new issue.

**Comment by RLovelett** [comment]
@iuriaranda I would have swore I came back to say thank you and that it helped a lot. I didn't mean to leave this issue hanging. Apologies, I did not.

Let me fix that, thank you and that helped a lot. 😄 👋

**Comment by iuriaranda** [comment]
No worries 🙂 
I'm glad I could help.
